### ISSUE TITLE
Configurable calendar event length

### ISSUE THREAD

**Issue by DanielleHuisman** [WoutervdBrink/Afval-iCal#1]
In https://github.com/WoutervdBrink/Afval-iCal/commit/83d53877ef472d2ec0793955c006f1cae6684424, you extended the length of the calendar event from 10 minutes to 2 hours, but it would be nice if this was configurable in the web interface. I can probably make a PR to implement it, but I would like to know your opinion on the feature first.

**Comment by WoutervdBrink** [comment]
The reason for the new length is that Calendar, at least on my phone, dismisses the notification after the 'event' has ended. The consequence is that the notification only appears for 10 minutes, then disappears.

I could add configurable event lengths, but if you know of a way to prevent Calendar from removing the notification I'm all ears as well :smile:

**Comment by DanielleHuisman** [comment]
I have notifications disabled for this calendar, so I don't have a solution for your notification issues. I just use this project to have the event visible in my calendar, so a block of 30 minutes would suffice for me. Making the event length configurable seems like a relatively simple solution for both use cases.

**Comment by WoutervdBrink** [comment]
@DanielleHuisman Finally got around to fixing this :smile:. In case you still use the website: you can now set the duration of the calendar item (between 10 minutes and 4 hours, in steps of 5 minutes). Let me know it that works for you, or if you encounter any issues.

**Comment by DanielleHuisman** [comment]
Works perfectly, thanks!

![image](https://github.com/WoutervdBrink/Afval-iCal/assets/7486186/1eb9e783-60ac-475c-a853-3a99c432ca89)
